# Isotope and MGS intersections

Input data:
* MGS: https://docs.google.com/spreadsheets/d/1Yx66yiwvQZNou-8_mej8KZ8imPBJNRJSOqJjJRPCy30/edit
* Isotope: "Isotope input data" folder on Drive

In [1]:
import sys; sys.path.append('..')
from crossreads_petrography.isotopes import *

Using user-specific config file: /Users/ryan/crossreads_petrography_data/config.yaml @ 2024-08-26 19:45:26,097
Initializing Config with yaml_path: /Users/ryan/crossreads_petrography_data/config.yaml @ 2024-08-26 19:45:26,097
Loading config from /Users/ryan/crossreads_petrography_data/config.yaml @ 2024-08-26 19:45:26,098
Config loaded and processed successfully @ 2024-08-26 19:45:26,102

In [2]:
isotoper = IsotopeConverter()

Initializing IsotopeConverter @ 2024-08-26 19:45:26,111

### Isotope intersections

In [3]:
isotoper.df_curves

Reading isotope curve data @ 2024-08-26 19:45:26,116

         marble_type          x         y
0        Paros-2 (3)  -3.583021  3.157248
2      Proconnesos-2  -9.126092  2.862408
3           Docimium -11.409500  4.077670
7            Göktepe  -3.268530  3.470874
8           Hymettus  -4.422843  2.293689
...              ...        ...       ...
4061  EphesosWhites1  -9.307172  3.005405
4081  EphesosWhites1  -9.144790  3.135135
4101  EphesosWhites1  -8.982409  3.254054
4121  EphesosWhites1  -8.779432  3.362162
4141  EphesosWhites1  -8.568336  3.524324

[1067 rows x 3 columns]

In [4]:
isotoper.df_points

    Sample     x     y
19      19 -1.31  3.19
51      51 -2.07  2.65
52      52 -6.67   2.6
57      57 -1.04  2.15
58      58 -1.99  1.83
..     ...   ...   ...
153    153 -6.96  2.41
154    154 -2.03  2.82
155    155 -3.84  3.54
156    156 -1.23  2.14
157    157  -1.5  1.77

[85 rows x 3 columns]

In [5]:
isotoper.df_intersections

,Aphrodisias,CapDeGardeScritto,Carrara,Docimium,EphesosBigio,EphesosScritto,EphesosWhites1,EphesosWhites2,FilfilaScritto,Göktepe,Hymettus,Naxos,Paros-1,Paros-2 (3),Paros-4,Pentelikon,Proconnesos-1,Proconnesos-2,Thasos-1 (2),Thasos-3
19,,,✔️,,,,,,✔️,,✔️,,,✔️,,,✔️,,✔️,
51,,,✔️,,,,,,✔️,✔️,✔️,,✔️,✔️,,,✔️,,✔️,
52,,,,✔️,,✔️,✔️,,✔️,,,✔️,,,,✔️,,✔️,,✔️
57,,,✔️,,,,,,✔️,,✔️,,,✔️,,,✔️,,✔️,
58,,,✔️,,,,,,✔️,,✔️,,✔️,✔️,,,✔️,,✔️,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,,,,✔️,✔️,✔️,✔️,,✔️,,,✔️,,,,✔️,,✔️,,✔️
154,,,✔️,,,,,,✔️,✔️,✔️,,✔️,✔️,,,✔️,,✔️,
155,,,,✔️,,,✔️,,✔️,,,,✔️,,,✔️,✔️,,,✔️
156,,,✔️,,,,,,✔️,,✔️,,,✔️,,,✔️,,✔️,
157,,,✔️,,,,,,✔️,,✔️,,,✔️,,,✔️,,✔️,

In [6]:
isotoper.plot()

### MGS intersections

Note: not really isotope related directly, but relates to marbles and also concerns intersections

In [7]:
read_path('mgs.input')

    value_mm value_type   subtype
0   0.278969     min wh   Carrara
1   0.493561    min box   Carrara
2   0.708154     median   Carrara
3   1.008583    max box   Carrara
4   1.373389     max wh   Carrara
..       ...        ...       ...
60  0.858369     min wh  Thasos-3
61  1.566523    min box  Thasos-3
62  1.802573     median  Thasos-3
63  2.875534    max box  Thasos-3
64  3.197423     max wh  Thasos-3

[65 rows x 3 columns]

In [8]:
isotoper.df_intersections_mgs

,Aphrodisias,CapDeGardeScritto,Carrara,Docimium,EphesosBigio,EphesosScritto,EphesosWhites1,EphesosWhites2,FilfilaScritto,Göktepe,Hymettus,Naxos,Paros-1,Paros-2 (3),Paros-4,Pentelikon,Proconnesos-1,Proconnesos-2,Thasos-1 (2),Thasos-3
ISic,,,,,,,,,,,,,,,,,,,,
ISic000097,🔬🔬🔍🔍,,,🔬🔬🔍,,,,,,🔬,,🔍,🔬🔬🔍🔍,🔬🔬🔍🔍,🔬🔬🔍🔍,🔬,🔬🔍🔍,,🔍,🔬🔍🔍
ISic000104,🔬🔍,,🔬🔬🔍🔍,🔬🔬🔍🔍,,,,,,🔬🔬🔍🔍,🔬🔍🔍,,🔬,🔬,,🔬🔬🔍,🔬,,,
ISic000121,🔬🔍🔍,,🔬🔬,🔬🔬,,,,,,🔬🔬,🔬,🔍,🔬🔍,🔬🔍🔍,🔍🔍,🔬🔬,🔬🔍🔍,,🔍,🔍🔍
ISic000148,🔬🔍,,🔬🔬🔍🔍,🔬🔬🔍🔍,,,,,,🔬🔬🔍🔍,🔬🔬🔍🔍,,,,,🔬🔍,,,,
ISic000579,🔬🔍,,🔬🔬🔍,🔬🔬🔍,,,,,,🔬🔬,🔬🔬,,,,,🔬🔍,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ISic000229,🔍,,🔍🔍,🔍🔍,,,,,,🔍🔍,🔍🔍,,,,,🔍,,,,
ISic000232,🔍,,🔍,🔍,,,,,,🔍,🔍,,,,,🔍,,,,
ISic001140,🔍🔍,,,,,,,,,,,🔍,🔍🔍,🔍🔍,🔍🔍,,🔍🔍,,🔍,🔍🔍
ISic001143,🔍,,🔍,🔍,,,,,,,,,,,,🔍,,,,
ISic001158,🔍,,🔍🔍,🔍🔍,,,,,,🔍🔍,🔍🔍,,,,,🔍,,,,

In [9]:
isotoper.run()

Processing isotope data @ 2024-08-26 19:45:26,712
Generating isotope outputs @ 2024-08-26 19:45:26,713
Saved: /Users/ryan/crossreads_petrography_data/isotopes/output/isotope_intersections.xlsx @ 2024-08-26 19:45:26,741
Saved: /Users/ryan/crossreads_petrography_data/isotopes/output/mgs_intersections.xlsx @ 2024-08-26 19:45:26,771
Saved: /Users/ryan/crossreads_petrography_data/isotopes/output/isotope_graph.png @ 2024-08-26 19:45:27,665
Saved: /Users/ryan/crossreads_petrography_data/isotopes/output/isotope_graph.html @ 2024-08-26 19:45:27,686
Saved: /Users/ryan/crossreads_petrography_data/isotopes/output/isotope_graph.pdf @ 2024-08-26 19:45:27,778