# Crossreads Petrography: pXRF Processing

In [1]:
import sys; sys.path.append('..')
from crossreads_petrography.pxrf import *
pd.options.display.max_columns = 1000

Loading config from /Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/notebooks/../data/default_config.yaml

In [2]:
xrf = PXRFConverter()
xrf

PXRFConverter(
    path = "/Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF",
    path_descriptions = "/Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF/pXRF Logbook new.xlsx",
    path_input = "/Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF/input",
    path_output = "/Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF/output",
    path_standards = "/Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF/pXRF Standards.xlsx",
)

In [3]:
xrf.get_description('Isic001838', 'c')

Loading pXRF descriptions

'white, support of globe, left'

In [4]:
# xrf.valid_elements

In [5]:
xrf.df_standards

Loading pXRF standard values

Unnamed: 0,0CC,10CC,20CC,30CC,40CC,50CC,60CC,70CC,80CC,90CC,100CC
Element,,,,,,,,,,,
SiO2,91.040645,84.721351,78.817028,73.795328,64.449734,55.454155,32.568351,27.167883,21.531343,11.572406,1.000000e-08
K2O,6.002285,5.585656,5.196385,4.865306,4.249153,3.656077,2.147222,1.791171,1.419556,0.762966,1.000000e-08
CaO,0.958449,7.880084,14.336479,19.820316,30.009677,39.799615,64.641336,70.491810,76.593960,87.366212,9.987017e+01
Fe2O3,1.998622,1.812909,1.650108,1.519050,1.291436,1.090152,0.643091,0.549136,0.455141,0.298417,1.298312e-01
Ba,120.000000,107.870481,97.275091,88.771005,74.055316,61.098357,32.508134,26.532239,20.565139,10.640721,0.000000e+00
Ce,195.000000,175.289532,158.072023,144.252883,120.339889,99.284830,52.825719,43.114889,33.418351,17.291171,0.000000e+00
Co,4.000000,3.595683,3.242503,2.959033,2.468511,2.036612,1.083604,0.884408,0.685505,0.354691,0.000000e+00
Cr,12.000000,10.787048,9.727509,8.877100,7.405532,6.109836,3.250813,2.653224,2.056514,1.064072,0.000000e+00
Cu,12.000000,10.790000,9.730000,8.880000,7.410000,6.110000,3.250000,2.650000,2.060000,1.060000,0.000000e+00
Fe,14261.000000,12890.263285,11692.895909,10731.863281,9068.867850,7604.623464,4373.690099,3698.364127,3024.032108,1902.490132,7.000000e+02
Mn,155.000000,140.105962,127.095705,116.653396,98.583757,82.673691,47.567280,40.229379,32.902277,20.715919,7.650000e+00
Ti,540.000000,488.095767,442.756327,406.365924,343.395040,287.950052,165.607726,140.035873,114.501658,72.033418,2.650000e+01
La,109.000000,97.982354,88.358208,80.633663,67.266912,55.497674,29.528222,24.100117,18.680001,9.665321,0.000000e+00
Nb,53.000000,47.642796,42.963165,39.207194,32.707765,26.985108,14.357759,11.718406,9.082936,4.699652,0.000000e+00
Ni,8.000000,7.191365,6.485006,5.918067,4.937021,4.073224,2.167209,1.768816,1.371009,0.709381,0.000000e+00
Pb,40.000000,35.956827,32.425030,29.590335,24.685105,20.366119,10.836045,8.844080,6.855046,3.546907,0.000000e+00
Rb,320.000000,287.654616,259.400243,236.722679,197.480843,162.928951,86.688359,70.752638,54.840371,28.375256,0.000000e+00
Sr,10.000000,14.144252,17.764344,20.669907,25.697767,30.124728,39.893054,41.934818,43.973577,47.364420,5.100000e+01
Th,51.000000,45.844954,41.341914,37.727677,31.473509,25.966802,13.815957,11.276202,8.740184,4.522306,0.000000e+00
V,2.000000,1.797841,1.621252,1.479517,1.234255,1.018306,0.541802,0.442204,0.342752,0.177345,0.000000e+00
Y,143.000000,128.545657,115.919483,105.785447,88.249252,72.808875,38.738860,31.617585,24.506791,12.680192,0.000000e+00
Zn,50.000000,44.946034,40.531288,36.987919,30.856382,25.457649,13.545056,11.055100,8.568808,4.433634,0.000000e+00
Zr,300.000000,269.676203,243.187728,221.927512,185.138290,152.745892,81.270336,66.330598,51.412848,26.601802,0.000000e+00
Hg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_desc=xrf.df_descriptions
df_desc[df_desc.Isic.str.contains('1838')]

,site,day,month,year,cass,inv/id,Isic,count analyses,metamorphic/sedimentary,pigment?,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
4,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
demo-MK,centuripe,,10,2023,,KA0843,ISic001838,6.0,m,,"white, top right corner","white, top centre","white, support of globe, left","gold, C","gold, R","gold, O",,,,,,,,,,,,,,,,,,,,

In [7]:
xrf.df_adjusted

Parsing pXRF measurements and calculating new fractions
Calculating linear regressions for standard values

NameError: name 'desc_rows' is not defined

In [ ]:
df = xrf.get_df_adjusted()
df[df.Isic.str.contains('1838')]
# df[(df.Isic.str.contains('1838')) & (df.desc!='')]

Parsing pXRF measurements and calculating new fractions

,Isic,Element,desc_category,desc,Fit_Area,Sigma_Area,Mass_fraction,m,q,y,Calc_fraction
8379,Isic001838,As,gold,"gold, C",166.537152,73.016667,0.000048,3.488925e+05,-2.085993,14.568741,8.897650
8380,Isic001838,Au,gold,"gold, C",120645.103333,370.500000,0.038047,9.430331e+04,-7.738295,3580.188488,2148.113093
8381,Isic001838,CaO,gold,"gold, C",391854.975000,590.750000,0.168747,1.536203e+02,-10.473347,20.641861,39.332648
8382,Isic001838,Co,gold,"gold, C",36.099602,25.383333,0.000004,7.113731e+04,0.373193,0.666693,0.400016
8383,Isic001838,Cr,gold,"gold, C",68.341293,21.083333,0.000025,1.079419e+05,1.708099,4.397291,2.638374
8384,Isic001838,Cu,gold,"gold, C",338.942983,30.650000,0.000062,1.739324e+05,-7.957246,2.770906,1.662544
8385,Isic001838,Fe,gold,"gold, C",5778.099000,80.416667,0.000924,1.207605e+06,1507.507966,2623.858010,1574.314806
8386,Isic001838,Fe2O3,gold,"gold, C",8234.991500,102.150000,0.001896,7.616615e+01,-0.090900,-0.052767,0.163537
8387,Isic001838,Hg,gold,"gold, C",460.765567,102.900000,0.000133,9.430331e+04,-7.738295,4.783928,3.519116
8388,Isic001838,K2O,gold,"gold, C",1100.201725,70.775000,0.000510,1.649790e+02,0.759291,1.270220,2.754813
8389,Isic001838,Mn,gold,"gold, C",95.187762,21.650000,0.000023,1.164880e+06,11.050559,37.825330,22.695198
8390,Isic001838,Nb,gold,"gold, C",230.408847,84.300000,0.000028,1.282119e+05,-0.896507,2.752488,0.842419
8391,Isic001838,Pb,gold,"gold, C",602.394550,119.000000,0.000152,9.430331e+04,-7.738295,6.587950,3.952770
8392,Isic001838,Rb,gold,"gold, C",1392.050322,120.350000,0.000212,9.735528e+04,12.072895,32.726752,19.636051
8393,Isic001838,SiO2,gold,"gold, C",133.237515,40.200000,0.007114,7.295548e+02,15.760861,26.570838,57.749001
8394,Isic001838,Sr,gold,"gold, C",33786.118333,213.833333,0.004732,8.117184e+03,2.754824,41.163986,24.698392
8395,Isic001838,Th,gold,"gold, C",351.053833,111.666667,0.000060,1.316832e+05,-9.272583,-1.310577,0.108957
8396,Isic001838,Ti,gold,"gold, C",154.620867,35.150000,0.000147,1.197956e+06,50.901722,226.941407,136.164844
8397,Isic001838,Y,gold,"gold, C",705.063133,79.916667,0.000093,1.137656e+05,4.194004,14.734386,8.840632
8398,Isic001838,Zn,gold,"gold, C",332.462338,51.200000,0.000051,3.488925e+05,-2.085993,15.851026,10.090398
8399,Isic001838,Zr,gold,"gold, C",122.867755,110.333333,0.000016,1.208168e+05,6.520199,8.395928,5.037557
8400,Isic001838,As,white,"white, top right corner",77.139669,64.783333,0.000023,3.488925e+05,-2.085993,5.813050,3.047995
8401,Isic001838,Au,white,"white, top right corner",292.243367,52.066667,0.000093,9.430331e+04,-7.738295,1.005037,0.502518
8402,Isic001838,CaO,white,"white, top right corner",562930.283333,717.833333,0.242415,1.536203e+02,-10.473347,26.071683,68.766690
8403,Isic001838,Co,white,"white, top right corner",14.294415,20.300000,0.000002,7.113731e+04,0.373193,0.497175,0.248588
8404,Isic001838,Cr,white,"white, top right corner",57.133650,17.300000,0.000022,1.079419e+05,1.708099,4.093614,2.046807
8405,Isic001838,Cu,white,"white, top right corner",354.105033,25.450000,0.000065,1.739324e+05,-7.957246,3.262265,1.631133
8406,Isic001838,Fe,white,"white, top right corner",5024.050667,72.666667,0.000858,1.207605e+06,1507.507966,2543.169889,1271.584944
8407,Isic001838,Fe2O3,white,"white, top right corner",10963.683333,119.966667,0.002626,7.616615e+01,-0.090900,0.224200,0.717542
8408,Isic001838,Hg,white,"white, top right corner",405.812750,61.683333,0.000120,9.430331e+04,-7.738295,3.593820,1.796910
8409,Isic001838,K2O,white,"white, top right corner",2346.002783,91.966667,0.001039,1.649790e+02,0.759291,0.407891,0.972933
8410,Isic001838,Mn,white,"white, top right corner",125.858233,19.583333,0.000032,1.164880e+06,11.050559,48.639301,24.319650
8411,Isic001838,Nb,white,"white, top right corner",371.822600,83.966667,0.000047,1.282119e+05,-0.896507,5.189283,1.297321
8412,Isic001838,Pb,white,"white, top right corner",955.808617,116.666667,0.000246,9.430331e+04,-7.738295,15.466607,7.733304
8413,Isic001838,Rb,white,"white, top right corner",355.535400,66.416667,0.000056,9.735528e+04,12.072895,17.502236,8.751118
8414,Isic001838,SiO2,white,"white, top right corner",75.175866,42.233333,0.004027,7.295548e+02,15.760861,9.080698,29.542835
8415,Isic001838,Sr,white,"white, top right corner",16638.690000,158.666667,0.002415,8.117184e+03,2.754824,22.357824,11.178912
8416,Isic001838,Th,white,"white, top right corner",670.493167,103.666667,0.000119,1.316832e+05,-9.272583,6.402109,1.600527
8417,Isic001838,Ti,white,"white, top right corner",155.437983,31.433333,0.000158,1.197956e+06,50.901722,239.939233,119.969617
8418,Isic001838,Y,white,"white, top right corner",366.345750,78.733333,0.000050,1.137656e+05,4.194004,9.848154,4.924077
8419,Isic001838,Zn,white,"white, top right corner",410.230967,27.166667,0.000064,3.488925e+05,-2.085993,20.384431,10.192215
8420,Isic001838,Zr,white,"white, top right corner",390.851533,99.733333,0.000051,1.208168e+05,6.520199,12.638363,6.319182

In [ ]:
df[df.desc_category!='']

,Isic,Element,desc_category,desc,Fit_Area,Sigma_Area,Mass_fraction,m,q,y,Calc_fraction
84,Isic000003,As,grey,"grey, below TYC",4.901010e+01,69.900000,0.000014,3.488925e+05,-2.085993,2.917591,1.656786
85,Isic000003,Au,grey,"grey, below TYC",2.246788e+02,52.200000,0.000071,9.430331e+04,-7.738295,-1.006610,0.003025
86,Isic000003,CaO,grey,"grey, below TYC",1.025640e+06,1043.000000,0.442867,1.536203e+02,-10.473347,59.060128,93.095453
87,Isic000003,Co,grey,"grey, below TYC",1.636612e+01,18.233333,0.000002,7.113731e+04,0.373193,0.512674,0.256337
88,Isic000003,Cr,grey,"grey, below TYC",6.210410e+01,17.466667,0.000024,1.079419e+05,1.708099,4.284671,2.142336
...,...,...,...,...,...,...,...,...,...,...,...
12259,IsicX04503,Th,white,"white, below serif",8.021089e+02,115.333333,0.000142,1.316832e+05,-9.272583,9.408876,2.352219
12260,IsicX04503,Ti,white,"white, below serif",6.554214e+01,30.516667,0.000065,1.197956e+06,50.901722,128.732946,64.366473
12261,IsicX04503,Y,white,"white, below serif",4.817234e+02,86.800000,0.000065,1.137656e+05,4.194004,11.591612,5.795806
12262,IsicX04503,Zn,white,"white, below serif",1.799514e+02,23.116667,0.000028,3.488925e+05,-2.085993,7.823136,3.911568
12263,IsicX04503,Zr,white,"white, below serif",4.697456e+02,111.666667,0.000061,1.208168e+05,6.520199,13.869487,6.934743

## Descriptions

This file lives on Google Drive on the Crossreads team drive. It contains notes about the samples, including the Isic codes.

In [ ]:
df=xrf.df_descriptions
df

,site,day,month,year,cass,inv/id,Isic,count analyses,metamorphic/sedimentary,pigment?,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
4,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
demo-MK,marpo,,11,2022,settore c,33038 or 33028,???,4.0,,y,"v, edge","v, other edge",o,"rubr, o",,,,,,,,,,,,,,,,,,,,,,
demo-MK,CT,,4,2024,,exmft001,CTexmft001,3.0,,,sample,sample,sample,,,,,,,,,,,,,,,,,,,,,,,
demo-MK,CT,27.0,3,2024,,exmft003,CTexmft003,4.0,,y,surface,sample,sample,"rubr, pigment",,,,,,,,,,,,,,,,,,,,,,
demo-MK,CT,27.0,3,2024,,exmft009,CTexmft009,1.0,,,thickness,,,,,,,,,,,,,,,,,,,,,,,,,
demo-MK,CT,27.0,3,2024,,exmft013,CTexmft013,3.0,,,fresh fracture,sample,sample,,,,,,,,,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
demo-MK,taormina,22.0,1,2024,,3555,taormina3555,12.0,,,"purple nodule, right","purple nodule, right","purple nodule, centre","grey, bottom right","grey, centre-right","grey, centre","black, left","black, left next to white","black, left","white, left","white, centre","white, left",,,,,,,,,,,,,,
demo-MK,tindari,,7,2024,,TIND004,tindariTIND004,4.0,,,white,white,grey,grey,,,,,,,,,,,,,,,,,,,,,,
demo-MK,tindari,,7,2024,,TIND005,tindariTIND005,3.0,,,sample,sample,sample,,,,,,,,,,,,,,,,,,,,,,,
demo-MK,tindari,,7,2024,,TIND007,tindariTIND007,3.0,,,sample,sample,sample,,,,,,,,,,,,,,,,,,,,,,,
demo-MK,tindari,,7,2024,,TIND008,tindariTIND008,3.0,,,"white, bottom right",grey,sample,,,,,,,,,,,,,,,,,,,,,,,

## Standards

In [ ]:
xrf.df_standards

Unnamed: 0,0CC,10CC,20CC,30CC,40CC,50CC,60CC,70CC,80CC,90CC,100CC
Element,,,,,,,,,,,
SiO2,91.040645,84.721351,78.817028,73.795328,64.449734,55.454155,32.568351,27.167883,21.531343,11.572406,1.000000e-08
K2O,6.002285,5.585656,5.196385,4.865306,4.249153,3.656077,2.147222,1.791171,1.419556,0.762966,1.000000e-08
CaO,0.958449,7.880084,14.336479,19.820316,30.009677,39.799615,64.641336,70.491810,76.593960,87.366212,9.987017e+01
Fe2O3,1.998622,1.812909,1.650108,1.519050,1.291436,1.090152,0.643091,0.549136,0.455141,0.298417,1.298312e-01
Ba,120.000000,107.870481,97.275091,88.771005,74.055316,61.098357,32.508134,26.532239,20.565139,10.640721,0.000000e+00
Ce,195.000000,175.289532,158.072023,144.252883,120.339889,99.284830,52.825719,43.114889,33.418351,17.291171,0.000000e+00
Co,4.000000,3.595683,3.242503,2.959033,2.468511,2.036612,1.083604,0.884408,0.685505,0.354691,0.000000e+00
Cr,12.000000,10.787048,9.727509,8.877100,7.405532,6.109836,3.250813,2.653224,2.056514,1.064072,0.000000e+00
Cu,12.000000,10.790000,9.730000,8.880000,7.410000,6.110000,3.250000,2.650000,2.060000,1.060000,0.000000e+00
Fe,14261.000000,12890.263285,11692.895909,10731.863281,9068.867850,7604.623464,4373.690099,3698.364127,3024.032108,1902.490132,7.000000e+02
Mn,155.000000,140.105962,127.095705,116.653396,98.583757,82.673691,47.567280,40.229379,32.902277,20.715919,7.650000e+00
Ti,540.000000,488.095767,442.756327,406.365924,343.395040,287.950052,165.607726,140.035873,114.501658,72.033418,2.650000e+01
La,109.000000,97.982354,88.358208,80.633663,67.266912,55.497674,29.528222,24.100117,18.680001,9.665321,0.000000e+00
Nb,53.000000,47.642796,42.963165,39.207194,32.707765,26.985108,14.357759,11.718406,9.082936,4.699652,0.000000e+00
Ni,8.000000,7.191365,6.485006,5.918067,4.937021,4.073224,2.167209,1.768816,1.371009,0.709381,0.000000e+00
Pb,40.000000,35.956827,32.425030,29.590335,24.685105,20.366119,10.836045,8.844080,6.855046,3.546907,0.000000e+00
Rb,320.000000,287.654616,259.400243,236.722679,197.480843,162.928951,86.688359,70.752638,54.840371,28.375256,0.000000e+00
Sr,10.000000,14.144252,17.764344,20.669907,25.697767,30.124728,39.893054,41.934818,43.973577,47.364420,5.100000e+01
Th,51.000000,45.844954,41.341914,37.727677,31.473509,25.966802,13.815957,11.276202,8.740184,4.522306,0.000000e+00
V,2.000000,1.797841,1.621252,1.479517,1.234255,1.018306,0.541802,0.442204,0.342752,0.177345,0.000000e+00
Y,143.000000,128.545657,115.919483,105.785447,88.249252,72.808875,38.738860,31.617585,24.506791,12.680192,0.000000e+00
Zn,50.000000,44.946034,40.531288,36.987919,30.856382,25.457649,13.545056,11.055100,8.568808,4.433634,0.000000e+00
Zr,300.000000,269.676203,243.187728,221.927512,185.138290,152.745892,81.270336,66.330598,51.412848,26.601802,0.000000e+00
Hg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## pXRF input data

Two kinds of files:
* "MK" files
    * Filename must start with 
    * Only Si, K, Ca, and Fe are included
* "t" files
    * Filenames must start with "t"
    * All elements with linear correlation with standard values (plus HG) are included

pXRF input data is processed in `df_measurements_with_standard_values`, attaching relevant standard values if present from `df_standards`.

In [ ]:
xrf.df_input

,filename,text
0,t tindari.txt,SOURCE: ISic000672-tK-a.csv\nKEY: 1.1.00001.1\...
1,t centuripe DEF.txt,SOURCE: ISic000655-t-a.csv\nKEY: 1.1.00001.1\n...
2,MK taormina.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
3,t marsala DEF.txt,SOURCE: t0-0CC-1.csv\nKEY: 1.1.00001.1\nElemen...
4,MK taormina DEF.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
5,t taormina DEF.txt,SOURCE: ISic000613-t-a.csv\nKEY: 1.1.00001.1\n...
6,t exmft DEF.txt,SOURCE: t0-0CC-1.csv\nKEY: 1.1.00001.1\nElemen...
7,t PCAS DEF.txt,SOURCE: ISic002713d-t-1.csv\nKEY: 1.1.00001.1\...
8,t termini DEF.txt,SOURCE: ISic000086-t-a.csv\nKEY: 1.1.00001.1\n...
9,MK salinas DEF.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
10,t halaesa.txt,SOURCE: HAL18-tK-a.csv\nKEY: 1.1.00001.1\nElem...
11,t CU DEF.txt,SOURCE: ISic000309-1t.csv\nKEY: 1.1.00001.1\nE...
12,MK tindari DEF.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
13,MK termini.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
14,t halaesa DEF.txt,SOURCE: ISic000584-tK-b.csv\nKEY: 1.1.00001.1\...
15,MK exmft DEF.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
16,t exmft.txt,SOURCE: t0-10CC-1.csv\nKEY: 1.1.00001.1\nEleme...
17,MK termini DEF.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
18,t centuripe.txt,SOURCE: ISic000655-t-a.csv\nKEY: 1.1.00001.1\n...
19,t MARPO DEF.txt,SOURCE: ISic000401-t-a.csv\nKEY: 1.1.00001.1\n...
20,MK marsala DEF.txt,SOURCE: ISic001661-MK-a.csv\nKEY: 1.1.00001.1\...
21,MK CU DEF.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
22,t Hg test.txt,SOURCE: cass27-ISic000368-1t.csv\nKEY: 1.1.000...
23,MK centuripe DEF.txt,SOURCE: ISic000655-t-a.csv\nKEY: 1.1.00001.1\n...
24,MK tindari.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
25,t Hg test with standards.txt,SOURCE: KA0863-t-a.csv\nKEY: 1.1.00001.1\nElem...
26,MK centuripe.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
27,MK exmft.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
28,MK MARPO DEF.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
29,t tindari DEF.txt,SOURCE: ISic000672-tK-a.csv\nKEY: 1.1.00001.1\...
30,MK PCAS DEF.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
31,MK halaesa DEF.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
32,MK halaesa.txt,SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement Gr...
33,t taormina.txt,SOURCE: capitellogrigio-t-a.csv\nKEY: 1.1.0000...
34,t termini.txt,SOURCE: ISic000086-t-a.csv\nKEY: 1.1.00001.1\n...
35,t salinas DEF.txt,SOURCE: ISic000003-t-a.csv\nKEY: 1.1.00001.1\n...

In [15]:
from data.pXRF.pxrf_coefficients import calculate_corrected_value
import pandas as pd

df_corrected = pd.DataFrame()

mk_elements = { "Si": "SiO2", "Ti": "TiO2", "Fe": "Fe2O3", "Mn": "MnO", "Ca": "CaO", "K": "K2O" }
t_elements = ["Ti", "Fe", "Mn", "Ca", "K", "Ba", "Co", "Cr", "Ni", "Pb", "Rb", "Sr", "V", "Y", "Zn", "Zr", "Fe", "Au", "Hg", "As", "Cu"]

txts = xrf.txt_input
for filename, txt in txts:
    is_mk = filename.startswith("MK")

    for content in txt.split("\n\n"):
        lines = content.split("\n")

        source_name = lines[0].split(":")[-1].strip().split(".")[0].strip()

        # is_isic = source_name.upper().startswith("ISIC")
        # if is_isic:
        #     source_name = source_name.split("-")[0].strip()

        if len(lines) < 3:
            continue

        header = lines[2].split()
        data = [ln.split() for ln in lines[3:]]
 
        df = pd.DataFrame(data, columns=header)
        df["Mass_fraction"] = df["Mass_fraction"].fillna(0).astype(float)

        if is_mk:
            df = df[df.Element.isin(mk_elements)]
            df = df.pivot_table(columns='Element', values='Mass_fraction', aggfunc='sum').reset_index(drop=True)

            df['total'] = df.sum(axis=1)

            for element in mk_elements.keys():
                df[element] = df[element] / df['total']
                df[element] = df[element].apply(lambda x: calculate_corrected_value('MK', element, x))

            df['total'] = df[mk_elements.keys()].sum(axis=1) 

            for element, element_corrected in mk_elements.items():
                df[element_corrected] = df[element] / df['total']

            df = df.drop(columns=list(mk_elements.keys()) + ['total'])
        else:
            df = df[df.Element.isin(t_elements)]
            df = df.pivot_table(columns='Element', values='Mass_fraction', aggfunc='sum').reset_index(drop=True)

            for element in t_elements:
                try:
                    df[element] = df[element].apply(lambda x: calculate_corrected_value('t', element, x))
                except ValueError as e:
                    df[element] = e

        df['ISic'] = source_name
        df = df.reset_index(drop=True)
        df = df.rename(columns={'index': 'Element'})
        df = df.set_index('ISic')

        df_corrected = pd.concat([df_corrected, df])

df_corrected = df_corrected.sort_index()
df_corrected.to_csv('../data/pXRF/output/corrected.csv')

In [17]:
xrf.run(pivot_table=True)  # hide all cols besides Calc_fraction

Processing pXRF data
Saving pXRF processed data
Parsing pXRF measurements and calculating new fractions
Parsing pXRF measurements and calculating new fractions
Saved: /Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF/output/2025-07-28/pXRF_calculated_fractions_mean.xlsx
Saved: /Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF/output/2025-07-28/pXRF_calculated_fractions_std.xlsx