In [1]:
import sys; sys.path.append('..')
from crossreads_petrography.xrd import *

In [2]:
xrd_converter = XRDConverter()

Initializing XRDConverter: /Users/ryan/github/crossreads-petrography/data/input/XRD / /content/drive/MyDrive/Crossreads B D1/XRD input data @ 2024-07-17 09:49:55,710
Authenticating and accessing Google Spreadsheet @ 2024-07-17 09:49:55,711

In [4]:
xrd_converter.df_xrd

Reading XRD data @ 2024-07-17 09:49:57,402
Reading XRD data from /Users/ryan/github/crossreads-petrography/data/input/XRD @ 2024-07-17 09:49:57,402
Reading dataframe from file: /Users/ryan/github/crossreads-petrography/data/input/XRD/xrd-results-tao.CSV @ 2024-07-17 09:49:57,403
Reading dataframe from file: /Users/ryan/github/crossreads-petrography/data/input/XRD/XRD-results-sample.CSV @ 2024-07-17 09:49:57,409
Read 426 rows from input data @ 2024-07-17 09:49:57,415

,XRD calcite content (%),XRD calcite content (%) ESD,XRD dolomite content (%),XRD dolomite content (%) ESD,XRD magnesian calcite content (%),XRD magnesian calcite content (%) ESD,XRD other minerals
Sample,,,,,,,
ISic000004,94.720,0.490,3.610,0.320,NaN,NaN,Qcalcitmg
ISic000034,85.400,1.000,3.060,0.270,NaN,NaN,Qcalcitmg
ISic000036,77.400,1.200,2.600,0.300,NaN,NaN,Qcalcitmg
ISic000068,0.000,0.000,1.200,1.300,NaN,NaN,QIron; QNa2SO14H20; Qcalcitmg; Qgypsum
ISic000069,94.830,0.330,NaN,NaN,NaN,NaN,QIron; Qquartz
ISic000097p,3.030,0.350,2.540,0.290,NaN,NaN,Qcalcitmg
ISic000104,81.900,1.200,1.600,0.310,NaN,NaN,Qcalcitmg
ISic000121,0.000,0.000,1.000,0.350,NaN,NaN,QIron; Qcalcitmg
ISic000148,17.520,0.690,2.220,0.260,NaN,NaN,QSiO2p3221; Qcalcitmg
ISic000163,95.400,7.900,0.120,0.210,NaN,NaN,Qcalcitmg
ISic000178,84.400,0.810,1.230,0.190,NaN,NaN,Qcalcitmg; Qorthoclase
ISic000207,91.590,0.630,1.600,0.250,NaN,NaN,Qcalcitmg
ISic000220,5.860,0.520,1.720,0.250,NaN,NaN,Qcalcitmg
ISic000227,85.300,1.100,1.850,0.250,NaN,NaN,Qcalcitmg
ISic000229,83.380,0.700,4.450,0.250,NaN,NaN,Qcalcitmg
ISic000232,38.200,6.100,2.100,0.320,NaN,NaN,Qcalcitmg
ISic000579,15.020,0.900,NaN,NaN,NaN,NaN,Qcalcitmg; Qmicroint2
ISic000725,1.350,0.120,98.500,0.140,0.15,0.095,
ISic000871,26.100,2.200,20.030,0.890,NaN,NaN,QMirabilite; Qcalcitmg; Qironalpha
ISic001120,88.140,0.610,1.610,0.250,NaN,NaN,Qcalcitmg
ISic001135,77.950,0.510,8.950,0.180,NaN,NaN,Qcalcitmg
ISic001399-1,NaN,NaN,32.700,1.400,NaN,NaN,QIron; QMirabilite; QOligoclase; QPhlogopite1M...
ISic003335,46.820,0.940,1.860,0.270,NaN,NaN,Qcalcitmg
ISic004341,66.200,2.300,2.530,0.430,NaN,NaN,QIron; Qcalcitmg
ISic004363,10.000,48.000,1.400,6.500,NaN,NaN,QIron; Qcalcitmg
ISic004364,83.200,1.400,1.680,0.290,NaN,NaN,Qcalcitmg
ISic004365,0.000,0.000,1.510,0.250,NaN,NaN,QIron; Qcalcitmg
tao100,98.590,0.210,0.800,0.160,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao105,95.920,0.350,0.186,0.077,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao106,97.430,0.370,0.790,0.150,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao227,99.560,0.150,0.340,0.140,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao240,98.590,0.150,0.242,0.065,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao31,96.110,0.700,0.590,0.270,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao5,28.720,0.820,0.940,0.320,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao57,99.680,0.100,0.270,0.098,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao60,97.740,0.480,0.850,0.160,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao63,12.330,0.170,0.391,0.088,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao64,97.570,0.440,0.900,0.190,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao64bis,99.553,0.082,0.447,0.082,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao67,98.940,0.150,0.117,0.040,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao67malta,72.730,0.580,1.260,0.210,NaN,NaN,QAragonite; QSiO2p3121; QSiO2p3221; Qalbint; Q...
tao69,98.170,0.380,0.460,0.150,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao7,7.930,0.360,0.510,0.170,NaN,NaN,QSiO2p3121; Qalbint; Qdiopside; Qhematite; Qmu...
tao74,98.390,0.180,1.200,0.110,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao87,97.470,0.180,2.220,0.140,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
tao90,94.620,0.620,2.610,0.200,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
taoLastraR,99.600,0.110,0.178,0.071,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
taoPiedi,88.050,0.220,11.320,0.160,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
taoSarcofago,98.960,0.160,0.450,0.100,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
taomascherome,99.220,0.370,0.190,0.140,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1
taoreclinato,99.591,0.084,0.339,0.081,NaN,NaN,QSiO2p3121; Qalbint; Qmusc2m1

In [5]:
xrd_converter.df_meta

Reading CrossReads sheet from Google Spreadsheet @ 2024-07-17 09:49:57,442
Reading data from spreadsheet worksheet 0 @ 2024-07-17 09:49:57,443
Read 177 rows from spreadsheet @ 2024-07-17 09:49:58,752

,entity type,rock type,rock desc1,rock desc2,visually assessed granulometry (very fine < 1mm; fine < 2mm; medium 2-5mm; coarse > 5mm),visually assessed colour,visually assessed sharpness of veins,visually assessed colour of veins,visually assessed protolith features,visually assessed monomineralic,...,EPR dolomite %,EPR width ave,EPR width stdevp,EPR g=2.0044 ave,EPR g=2.0044 stdevp,EPR g=14.2515 ave,EPR g=14.2515 stdevp,XRD clay minerals,XRD K-feldspar,XRD plagioclase
reference or rock id,,,,,,,,,,,,,,,,,,,,,
Capedri et al 2004,reference,marble,carrara,,,,,,,,...,,,,,,,,0,0,0
Antonelli and Nestola 2021,reference,marble,carrara,,very fine,white/whitish,edgeless veins,grey to black,,,...,,,,,,,,0,0,0
Antonelli and Nestola 2021,reference,marble,göktepe,,very fine,white/whitish,,,,,...,,,,,,,,0,0,0
Antonelli and Lazzarini 2015,reference,marble,carrara,"fantiscritti, ravaccione, fossacava",very fine,white/whitish,edgeless and sharp veins,grey to black,no,yes,...,,,,,,,,0,0,0
Antonelli and Lazzarini 2015,reference,marble,paros-1,lychnites - stephani (marathi),fine,white/whitish,,,no,yes,...,,,,,,,,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
taoLastraR,,,,,,,,,,,...,,,,,,,,0,0,0
taoPiedi,,,,,,,,,,,...,,,,,,,,0,0,0
taoSarcofago,,,,,,,,,,,...,,,,,,,,0,0,0
taomascherome,,,,,,,,,,,...,,,,,,,,0,0,0
taoreclinato,,,,,,,,,,,...,,,,,,,,0,0,0

In [6]:
xrd_converter.df_updated

Updating CrossReads sheet with XRD data @ 2024-07-17 09:49:58,768
Updated 0 values in 0 samples @ 2024-07-17 09:49:58,785

In [7]:
xrd_converter.save()

No updates to apply @ 2024-07-17 09:49:58,790

In [8]:
xrd_converter.run()

No updates to apply @ 2024-07-17 09:49:58,795