In [1]:
import sys; sys.path.append('..')
from crossreads_petrography import *

Using user-specific config file: /Users/ryan/crossreads_petrography_data/config.yaml @ 2024-08-26 18:21:16,577
Initializing Config with yaml_path: /Users/ryan/crossreads_petrography_data/config.yaml @ 2024-08-26 18:21:16,578
Loading config from /Users/ryan/crossreads_petrography_data/config.yaml @ 2024-08-26 18:21:16,578
Config loaded and processed successfully @ 2024-08-26 18:21:16,583

In [2]:
xrd_converter = XRDConverter()

In [3]:
xrd_converter.df_input

,File,Sample,Sample ID,"Parameter, Goal",Value,ESD
0,E:/nextcloud/ISicily/petrography/XRD/001207vg.lst,001207vg,,QCalcite,0.00441,"0.00085,"
1,E:/nextcloud/ISicily/petrography/XRD/001207vg.lst,001207vg,,Qquartz,0.40860,"0.0033,"
2,E:/nextcloud/ISicily/petrography/XRD/001207vg.lst,001207vg,,Qmicroint2,0.09400,"0.0025,"
3,E:/nextcloud/ISicily/petrography/XRD/001207vg.lst,001207vg,,Qmusc2m1,0.13600,"0.0044,"
4,E:/nextcloud/ISicily/petrography/XRD/001207vg.lst,001207vg,,Qchlorite2b,0.05540,"0.0023,"
...,...,...,...,...,...,...
201,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,004365,,QIron,0.05320,0.0022
202,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,004365,,Rwp,11.80000,
203,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,004365,,Rexp,11.65000,
204,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,004365,,Chi2,1.02590,
205,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,004365,,GOF,1.01290,

In [4]:
xrd_converter.df_mineral_types

              subtype                      colname      category
0                   *           XRD other minerals           NaN
1             QALBINT       XRD albite content (%)   Plagioclase
2             Qalbint       XRD albite content (%)           NaN
3             QAlbite       XRD albite content (%)   Plagioclase
4           QAnalbite       XRD albite content (%)   Plagioclase
..                ...                          ...           ...
82          QSanina75  XRD Na-sanidine content (%)           NaN
83          QSANINA85  XRD Na-sanidine content (%)           NaN
84         QSiO2p3121       XRD quartz content (%)           NaN
85         QSiO2p3221       XRD quartz content (%)           NaN
86  Qsmectitedi2wfix1     XRD smectite content (%)  Clay Mineral

[87 rows x 3 columns]

In [7]:
xrd_converter.df_xrd

,XRD calcite content (%),XRD calcite content (%) ESD,XRD quartz content (%),XRD quartz content (%) ESD,XRD microcline content (%),XRD microcline content (%) ESD,XRD muscovite content (%),XRD muscovite content (%) ESD,XRD chlorite content (%),XRD chlorite content (%) ESD,...,XRD Na-sanidine content (%),XRD Na-sanidine content (%) ESD,XRD kaolinite content (%),XRD kaolinite content (%) ESD,XRD andesine content (%),XRD andesine content (%) ESD,XRD other minerals,XRD Clay Mineral,XRD K_Feldspar,XRD Plagioclase
Sample,,,,,,,,,,,,,,,,,,,,,
ISic000004,96.39,0.87,,,,,,,,,...,,,,,,,,0.000,0.0,0.00
ISic000009grey,100.0,0.0,,,,,,,,,...,,,,,,,,0.000,0.0,0.00
ISic000009pink,87.45,0.38,,,,,,,,,...,,,8.24,0.33,,,Qcerussite; Qhydrotalcite,8.240,0.0,0.00
ISic000015,100.0,0.0,,,,,,,,,...,,,,,,,,0.000,0.0,0.00
ISic000017,100.0,0.0,,,,,,,,,...,,,,,,,,0.000,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
taoLastraR,99.6,0.11,0.0,0.0,,,0.225,0.074,,,...,,,,,,,,0.225,0.0,0.00
taoPiedi,88.05,0.22,0.025,0.062,,,0.59,0.15,,,...,,,,,,,,0.590,0.0,0.00
taoSarcofago,98.96,0.16,0.242,0.048,,,0.35,0.11,,,...,,,,,,,,0.350,0.0,0.00
taomascherome,99.22,0.37,0.13,0.13,,,0.0,0.0,,,...,,,,,,,,0.000,0.0,0.46
taoreclinato,99.591,0.084,0.07,0.021,,,0.0,0.0,,,...,,,,,,,,0.000,0.0,0.00

In [6]:
xrd_converter.run()

Postprocessing XRD data @ 2024-08-26 18:21:17,126
Saved: xrd_data_postprocessed.xlsx @ 2024-08-26 18:21:17,200