In [1]:
import sys; sys.path.append('..')
from crossreads_petrography.xrd import *

In [2]:
xrd_converter = XRDConverter()

Initializing XRDConverter: /Users/ryan/github/crossreads-petrography/data/input/XRD / /content/drive/MyDrive/Crossreads B D1/XRD input data @ 2024-07-17 09:18:40,951
Authenticating and accessing Google Spreadsheet @ 2024-07-17 09:18:40,952

In [3]:
xrd_converter.df_xrd

Reading XRD data @ 2024-07-17 09:18:45,922
Reading XRD data from /Users/ryan/github/crossreads-petrography/data/input/XRD @ 2024-07-17 09:18:45,923
Reading dataframe from file: /Users/ryan/github/crossreads-petrography/data/input/XRD/xrd-results-tao.CSV @ 2024-07-17 09:18:45,924
Reading dataframe from file: /Users/ryan/github/crossreads-petrography/data/input/XRD/XRD-results-sample.CSV @ 2024-07-17 09:18:45,931
Read 426 rows from input data @ 2024-07-17 09:18:45,936

,XRD calcite content (%),XRD calcite content (%) ESD,XRD dolomite content (%),XRD dolomite content (%) ESD,XRD other minerals
Sample,,,,,
tao100,98.590,0.210,0.800,0.160,QSiO2p3121; Qalbint; Qmusc2m1
tao105,95.920,0.350,0.186,0.077,QSiO2p3121; Qalbint; Qmusc2m1
tao106,97.430,0.370,0.790,0.150,QSiO2p3121; Qalbint; Qmusc2m1
tao227,99.560,0.150,0.340,0.140,QSiO2p3121; Qalbint; Qmusc2m1
tao240,98.590,0.150,0.242,0.065,QSiO2p3121; Qalbint; Qmusc2m1
tao31,96.110,0.700,0.590,0.270,QSiO2p3121; Qalbint; Qmusc2m1
tao5,28.720,0.820,0.940,0.320,QSiO2p3121; Qalbint; Qmusc2m1
tao57,99.680,0.100,0.270,0.098,QSiO2p3121; Qalbint; Qmusc2m1
tao60,97.740,0.480,0.850,0.160,QSiO2p3121; Qalbint; Qmusc2m1
tao63,12.330,0.170,0.391,0.088,QSiO2p3121; Qalbint; Qmusc2m1
tao64,97.570,0.440,0.900,0.190,QSiO2p3121; Qalbint; Qmusc2m1
tao64bis,99.553,0.082,0.447,0.082,QSiO2p3121; Qalbint; Qmusc2m1
tao67,98.940,0.150,0.117,0.040,QSiO2p3121; Qalbint; Qmusc2m1
tao67malta,72.730,0.580,1.260,0.210,QAragonite; QSiO2p3121; QSiO2p3221; Qalbint; Q...
tao69,98.170,0.380,0.460,0.150,QSiO2p3121; Qalbint; Qmusc2m1
tao7,7.930,0.360,0.510,0.170,QSiO2p3121; Qalbint; Qdiopside; Qhematite; Qmu...
tao74,98.390,0.180,1.200,0.110,QSiO2p3121; Qalbint; Qmusc2m1
tao87,97.470,0.180,2.220,0.140,QSiO2p3121; Qalbint; Qmusc2m1
tao90,94.620,0.620,2.610,0.200,QSiO2p3121; Qalbint; Qmusc2m1
taoLastraR,99.600,0.110,0.178,0.071,QSiO2p3121; Qalbint; Qmusc2m1
taoPiedi,88.050,0.220,11.320,0.160,QSiO2p3121; Qalbint; Qmusc2m1
taoSarcofago,98.960,0.160,0.450,0.100,QSiO2p3121; Qalbint; Qmusc2m1
taomascherome,99.220,0.370,0.190,0.140,QSiO2p3121; Qalbint; Qmusc2m1
taoreclinato,99.591,0.084,0.339,0.081,QSiO2p3121; Qalbint; Qmusc2m1

In [7]:
xrd_converter.df_meta

Reading CrossReads sheet from Google Spreadsheet @ 2024-07-17 09:08:32,032
Reading data from spreadsheet worksheet 0 @ 2024-07-17 09:08:32,032
Read 177 rows from spreadsheet @ 2024-07-17 09:08:33,745

,entity type,rock type,rock desc1,rock desc2,visually assessed granulometry (very fine < 1mm; fine < 2mm; medium 2-5mm; coarse > 5mm),visually assessed colour,visually assessed sharpness of veins,visually assessed colour of veins,visually assessed protolith features,visually assessed monomineralic,...,EPR dolomite %,EPR width ave,EPR width stdevp,EPR g=2.0044 ave,EPR g=2.0044 stdevp,EPR g=14.2515 ave,EPR g=14.2515 stdevp,XRD clay minerals,XRD K-feldspar,XRD plagioclase
reference or rock id,,,,,,,,,,,,,,,,,,,,,
Capedri et al 2004,reference,marble,carrara,,,,,,,,...,,,,,,,,0,0,0
Antonelli and Nestola 2021,reference,marble,carrara,,very fine,white/whitish,edgeless veins,grey to black,,,...,,,,,,,,0,0,0
Antonelli and Nestola 2021,reference,marble,göktepe,,very fine,white/whitish,,,,,...,,,,,,,,0,0,0
Antonelli and Lazzarini 2015,reference,marble,carrara,"fantiscritti, ravaccione, fossacava",very fine,white/whitish,edgeless and sharp veins,grey to black,no,yes,...,,,,,,,,0,0,0
Antonelli and Lazzarini 2015,reference,marble,paros-1,lychnites - stephani (marathi),fine,white/whitish,,,no,yes,...,,,,,,,,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
taoLastraR,,,,,,,,,,,...,,,,,,,,0,0,0
taoPiedi,,,,,,,,,,,...,,,,,,,,0,0,0
taoSarcofago,,,,,,,,,,,...,,,,,,,,0,0,0
taomascherome,,,,,,,,,,,...,,,,,,,,0,0,0
taoreclinato,,,,,,,,,,,...,,,,,,,,0,0,0

In [8]:
xrd_converter.df_updated

Updating CrossReads sheet with XRD data @ 2024-07-17 09:08:35,670
Updated 0 values in 0 samples @ 2024-07-17 09:08:35,680

In [9]:
xrd_converter.run()