# Crossreads Petrography Analysis
This notebook demonstrates the use of the `crossreads-petrography` library for analyzing petrographic data. It includes steps for cloning the repository, installing the library, and exploring its configuration and functionality.

In [3]:
#@title Installing code
!wget -q https://raw.githubusercontent.com/tsunrise/colab-github/main/colab_github.py
import colab_github
colab_github.github_auth(persistent_key=True)
repo_addr="git@github.com:kingsdigitallab/crossreads-petrography.git"
!git clone "$repo_addr"
!pip install -q -r crossreads-petrography/requirements.txt
import sys; sys.path.append('./crossreads-petrography')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
Looks that a private key is already created. If you have already push it to github, no action required.
 Otherwise, Please go to https://github.com/settings/ssh/new to upload the following key:
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGlSYV7PoFlphOEPB+yk1ZuDax3X56e0FY7KPVVnEQc5 root@0ef1b1ee2fd3

Please use SSH method to clone repo.
fatal: destination path 'crossreads-petrography' already exists and is not an empty directory.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 1.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 9.3 MB/s eta 0:00:00

In [4]:
# @title Loading library and config
from crossreads_petrography import XRDConverter

User-specific config not found. Using default config: /content/crossreads-petrography/data/default_config.yaml @ 2024-08-26 18:47:53,715
Initializing Config with yaml_path: /content/crossreads-petrography/data/default_config.yaml @ 2024-08-26 18:47:53,717
Loading config from /content/crossreads-petrography/data/default_config.yaml @ 2024-08-26 18:47:53,722
Config loaded and processed successfully @ 2024-08-26 18:47:53,734

In [5]:
xrd_converter = XRDConverter()
xrd_converter.paths

Using Colab-specific value for key paths.data: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data @ 2024-08-26 18:47:55,098
Using Colab-specific value for key paths.isotopes: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/isotopes @ 2024-08-26 18:47:55,100
Using Colab-specific value for key paths.isotopes.input: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/isotopes/input @ 2024-08-26 18:47:55,101
Using Colab-specific value for key paths.isotopes.output: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/isotopes/output @ 2024-08-26 18:47:55,106
Using Colab-specific value for key paths.metadata: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/metadata @ 2024-08-26 18:47:55,108
Using Colab-specific value for key paths.metadata.metamorphic: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/metadata/Metamorphic.xlsx @ 2024-08-26 18:47:55,110
Using Colab-specific value for key paths.metadata.sedimentary: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/metadata/Sedimentary.xlsx @ 2024-08-26 18:47:55,112
Using Colab-specific value for key paths.mgs: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/mgs @ 2024-08-26 18:47:55,114
Using Colab-specific value for key paths.mgs.input: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/mgs/input @ 2024-08-26 18:47:55,116
Using Colab-specific value for key paths.mgs.output: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/mgs/output @ 2024-08-26 18:47:55,117
Using Colab-specific value for key paths.pxrf: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pxrf @ 2024-08-26 18:47:55,119
Using Colab-specific value for key paths.pxrf.descriptions: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pxrf/pxrf_logbook.xlsx @ 2024-08-26 18:47:55,121
Using Colab-specific value for key paths.pxrf.input: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pxrf/input @ 2024-08-26 18:47:55,123
Using Colab-specific value for key paths.pxrf.output: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pxrf/output @ 2024-08-26 18:47:55,124
Using Colab-specific value for key paths.pxrf.standards: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pxrf/pxrf_standards.xlsx @ 2024-08-26 18:47:55,126
Using Colab-specific value for key paths.root: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data @ 2024-08-26 18:47:55,127
Using Colab-specific value for key paths.xrd: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/xrd @ 2024-08-26 18:47:55,129
Using Colab-specific value for key paths.xrd.input: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/xrd/input @ 2024-08-26 18:47:55,131
Using Colab-specific value for key paths.xrd.mineral_types: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/xrd/mineral_categories.xlsx @ 2024-08-26 18:47:55,136
Using Colab-specific value for key paths.xrd.output: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/xrd/output @ 2024-08-26 18:47:55,137

{'input': '/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/xrd/input',
 'mineral_types': '/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/xrd/mineral_categories.xlsx',
 'output': '/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/xrd/output'}

In [7]:
xrd_converter.df_input

,File,Sample,Sample ID,"Parameter, Goal",Value,ESD
0,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,000004,,Qcalcite,0.9472,0.0049
1,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,000004,,Qcalcitmg,0.0167,0.0038
2,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,000004,,Qdolomite,0.0361,0.0032
3,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,000004,,Rwp,4.8400,
4,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,000004,,Rexp,5.6100,
...,...,...,...,...,...,...
187,E:/nextcloud/ISicily/petrography/XRD/001482vg.lst,001482vg,,Qnontronite,0.0218,"0.002,"
188,E:/nextcloud/ISicily/petrography/XRD/001482vg.lst,001482vg,,Rwp,8.0700,","
189,E:/nextcloud/ISicily/petrography/XRD/001482vg.lst,001482vg,,Rexp,6.3500,","
190,E:/nextcloud/ISicily/petrography/XRD/001482vg.lst,001482vg,,Chi2,1.6151,","
191,E:/nextcloud/ISicily/petrography/XRD/001482vg.lst,001482vg,,GOF,1.2709,","

In [8]:
xrd_converter.df_mineral_types

              subtype                      colname      category
0                   *           XRD other minerals           NaN
1             QALBINT       XRD albite content (%)   Plagioclase
2             Qalbint       XRD albite content (%)           NaN
3             QAlbite       XRD albite content (%)   Plagioclase
4           QAnalbite       XRD albite content (%)   Plagioclase
..                ...                          ...           ...
82          QSanina75  XRD Na-sanidine content (%)           NaN
83          QSANINA85  XRD Na-sanidine content (%)           NaN
84         QSiO2p3121       XRD quartz content (%)           NaN
85         QSiO2p3221       XRD quartz content (%)           NaN
86  Qsmectitedi2wfix1     XRD smectite content (%)  Clay Mineral

[87 rows x 3 columns]

In [9]:
xrd_converter.df_output

ESD (0.88) is larger than value (0.87) for ISic000068 on qcalcitmg @ 2024-08-26 18:48:32,118
ESD (0.013) is larger than value (0.012) for ISic000068 on qdolomite @ 2024-08-26 18:48:32,123
ESD (0.97) is larger than value (0.04) for ISic000068 on qiron @ 2024-08-26 18:48:32,127
ESD (0.025) is larger than value (0.024) for ISic000068 on qgypsum @ 2024-08-26 18:48:32,135
ESD (0.077) is larger than value (0.045) for ISic000163 on qcalcitmg @ 2024-08-26 18:48:32,181
ESD (0.0021) is larger than value (0.0012) for ISic000163 on qdolomite @ 2024-08-26 18:48:32,185
ESD (0.48) is larger than value (0.1) for ISic004363 on qcalcite @ 2024-08-26 18:48:32,292
ESD (3.6) is larger than value (0.8) for ISic004363 on qcalcitmg @ 2024-08-26 18:48:32,297
ESD (0.065) is larger than value (0.014) for ISic004363 on qdolomite @ 2024-08-26 18:48:32,303
ESD (4.2) is larger than value (0.1) for ISic004363 on qiron @ 2024-08-26 18:48:32,310
ESD (0.0028) is larger than value (0.0016) for tao31 on qmusc2m1 @ 2024-08-26 18:48:32,359
ESD (0.00062) is larger than value (0.00025) for taoPiedi on qsio2p3121 @ 2024-08-26 18:48:32,566
ESD (0.76) is larger than value (0.54) for ISic001138pvg on qcalcite @ 2024-08-26 18:48:33,026
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qmusc2m1 @ 2024-08-26 18:48:33,032
ESD (0.91) is larger than value (0.36) for ISic001138pvg on qkaolinitedis @ 2024-08-26 18:48:33,037
ESD (0.006) is larger than value (0.0042) for ISic001138pvg on qhematite @ 2024-08-26 18:48:33,042
ESD (0.06) is larger than value (0.042) for ISic001138pvg on qchlorite2b @ 2024-08-26 18:48:33,046
ESD (0.017) is larger than value (0.012) for ISic001138pvg on qquartz @ 2024-08-26 18:48:33,053
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qalbite @ 2024-08-26 18:48:33,059
ESD (0.0048) is larger than value (0.0034) for ISic001138pvg on qenstatitemg06fe04ca @ 2024-08-26 18:48:33,065
ESD (0.0089) is larger than value (0.0061) for ISic001138pvg on qenstatite @ 2024-08-26 18:48:33,073
ESD (0.00047) is larger than value (0.00032) for ISic001138pvg on qsylvite @ 2024-08-26 18:48:33,077
ESD (94.0) is larger than value (1.0) for ISic003373vg on qcalcite @ 2024-08-26 18:48:33,190
ESD (1.3) is larger than value (0.0) for ISic003373vg on qquartz @ 2024-08-26 18:48:33,196
ESD (96.0) is larger than value (0.0) for ISic003373vg on qchloritfxbg @ 2024-08-26 18:48:33,202

,XRD calcite content (%),XRD calcite content (%) ESD,XRD dolomite content (%),XRD dolomite content (%) ESD,nan,nan ESD,XRD quartz content (%),XRD quartz content (%) ESD,XRD orthoclase content (%),XRD orthoclase content (%) ESD,...,XRD anorthite content (%),XRD anorthite content (%) ESD,XRD andesine content (%),XRD andesine content (%) ESD,XRD K-sanidine content (%),XRD K-sanidine content (%) ESD,XRD other minerals,XRD Clay Mineral,XRD K_Feldspar,XRD Plagioclase
Sample,,,,,,,,,,,,,,,,,,,,,
ISic000004,96.39,0.87,3.61,0.32,,,,,,,...,,,,,,,,0.000,0.0,0.00
ISic000009grey,100.0,0.0,,,,,,,,,...,,,,,,,,0.000,0.0,0.00
ISic000009pink,87.45,0.38,2.87,0.18,,,,,,,...,,,,,,,Qcerussite; Qhydrotalcite,8.240,0.0,0.00
ISic000015,100.0,0.0,,,,,,,,,...,,,,,,,,0.000,0.0,0.00
ISic000017,100.0,0.0,,,,,,,,,...,,,,,,,,0.000,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
taoLastraR,99.6,0.11,0.178,0.071,,,0.0,0.0,,,...,,,,,,,,0.225,0.0,0.00
taoPiedi,88.05,0.22,11.32,0.16,,,0.025,0.062,,,...,,,,,,,,0.590,0.0,0.00
taoSarcofago,98.96,0.16,0.45,0.1,,,0.242,0.048,,,...,,,,,,,,0.350,0.0,0.00
taomascherome,99.22,0.37,0.19,0.14,,,0.13,0.13,,,...,,,,,,,,0.000,0.0,0.46
taoreclinato,99.591,0.084,0.339,0.081,,,0.07,0.021,,,...,,,,,,,,0.000,0.0,0.00

In [10]:
xrd_converter.run()

Postprocessing XRD data @ 2024-08-26 18:48:34,666
Saved: /content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/xrd/output/xrd_data_postprocessed.xlsx @ 2024-08-26 18:48:35,190