# Crossreads Petrography: pXRF

### Input data

1. Correction coefficients from manual calculation: [/pXRF/Coefficients.xlsx](https://docs.google.com/spreadsheets/d/1TEdjc9gaXEC-oL6GzfT9o0oni8ysjB8c/edit?usp=share_link&ouid=112883786736398320585&rtpof=true&sd=true)
2. Descriptions of samples for pXRF, keyed partly by ISic code (there are multiple rows per ISic in some cases): [/pXRF/pXRF Logbook.xlsx](https://docs.google.com/spreadsheets/d/1_GGnrOeyxBbg4KSSPqa0VXGa-NCX_0Bw/edit?usp=drive_link&ouid=102758595970305145284&rtpof=true&sd=true)
3. pXRF input .txt files, with raw data from the pXRF measurement tool: [/pXRF/input](https://drive.google.com/drive/folders/13lJS0Q2HDCItCUiKYGeZDNkWjvP-M9R-)

### Output data

* An Excel file containing the calculated fractions for each element, saved as 'pXRF_calculated_fractions.xlsx' in the output folder: [/pXRF/output](https://drive.google.com/drive/folders/1Hw0ptsXg7FtzpGPcBWN-ekx-FDdhXEhy?usp=drive_link). The output includes adjusted values based on linear regressions calculated from the standard values, along with additional metadata such as source names and descriptions from the logbook.

In [ ]:
# @title Installing crossreads-petrography from github
!wget -q https://gist.githubusercontent.com/alessiacoccato/a1f9b9ff5530bfcdcf084b77513358b2/raw/crossreads_petrography_installer.py
import crossreads_petrography_installer
crossreads_petrography_installer.install()

Google Drive already mounted
Pulling repository crossreads-petrography
Pulled repository crossreads-petrography
Installing requirements for crossreads-petrography
Installed requirements for crossreads-petrography
Installation of crossreads_petrography version 0.2.0 successful.
Running tests with verbosity: q

....................F.................................F...........                           [100%]

Some tests failed

============================================= FAILURES =============================================
___________________________________ TestPXRFConverter.test_save ____________________________________

self = <test_converter.TestPXRFConverter object at 0x7e9bdf694bd0>
mock_to_excel = <MagicMock name='to_excel' id='139207904712848'>
converter = PXRFConverter(
    path = "/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pXRF",
    path_descript...,
    path_standards = "/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pXRF/pXRF Standards.xlsx",
)
tmp_path = PosixPath('/tmp/pytest-of-root/pytest-3/test_save1')

    @patch('pandas.DataFrame.to_excel')
    def test_save(self, mock_to_excel, converter, tmp_path):
        converter.paths['output'] = str(tmp_path)

        # Mock the DataFrame.to_excel method to create an empty file
        def to_excel_side_effect(filename, *args, **kwargs):
            file_path = Path(filename)
            file_path.parent.mkdir(parents=True, exist_ok=True)  # Create parent directories
            file_path.touch()  # Create an empty file

        mock_to_excel.side_effect = to_excel_side_effect

>       converter.save()

crossreads-petrography/tests/test_converter.py:54:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
crossreads-petrography/crossreads_petrography/pxrf.py:359: in save
    df_mean = self.get_df_adjusted(agg_stdev=False).reset_index()
crossreads-petrography/crossreads_petrography/pxrf.py:204: in get_df_adjusted
    sdf = self.df_linreg
/usr/lib/python3.11/functools.py:1001: in __get__
    val = self.func(instance)
crossreads-petrography/crossreads_petrography/pxrf.py:169: in df_linreg
    df = self.df_standards_parsed
/usr/lib/python3.11/functools.py:1001: in __get__
    val = self.func(instance)
crossreads-petrography/crossreads_petrography/pxrf.py:149: in df_standards_parsed
    df = pd.concat(o)
/usr/local/lib/python3.11/dist-packages/pandas/core/reshape/concat.py:382: in concat
    op = _Concatenator(
/usr/local/lib/python3.11/dist-packages/pandas/core/reshape/concat.py:445: in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pandas.core.reshape.concat._Concatenator object at 0x7e9be1cdb710>, objs = [], keys = None

    def _clean_keys_and_objs(
        self,
        objs: Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame],
        keys,
    ) -> tuple[list[Series | DataFrame], Index | None]:
        if isinstance(objs, abc.Mapping):
            if keys is None:
                keys = list(objs.keys())
            objs_list = [objs[k] for k in keys]
        else:
            objs_list = list(objs)

        if len(objs_list) == 0:
>           raise ValueError("No objects to concatenate")
E           ValueError: No objects to concatenate

/usr/local/lib/python3.11/dist-packages/pandas/core/reshape/concat.py:507: ValueError
___________________________ TestMGSIntegration.test_not_too_many_symbols ___________________________

self = <test_integration.TestMGSIntegration object at 0x7e9bdf6e99d0>
mgs = MgsConverter(
    path = "/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/MGS",
    path_input = "/...y_data/MGS/input",
    path_output = "/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/MGS/output",
)

    def test_not_too_many_symbols(self, mgs):
        for i,row in mgs.df_output.iterrows():
            for k,v in row.items():
                assert type(v) is str, 'Not string value'
>               assert v.count('🔍')<=2, 'Too many symbols'
E               AssertionError: Too many symbols
E               assert 3 <= 2
E                +  where 3 = <built-in method count of str object at 0x7e9bdddc71b0>('🔍')
E                +    where <built-in method count of str object at 0x7e9bdddc71b0> = '🔍🔍🔍'.count

crossreads-petrography/tests/test_integration.py:51: AssertionError
===================================== short test summary info ======================================
FAILED crossreads-petrography/tests/test_converter.py::TestPXRFConverter::test_save - ValueError:...
FAILED crossreads-petrography/tests/test_integration.py::TestMGSIntegration::test_not_too_many_symbols
2 failed, 64 passed in 14.77s

In [ ]:
from crossreads_petrography.pxrf import *

In [ ]:
xrf = PXRFConverter()
xrf

PXRFConverter(
    path = "/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pXRF",
    path_descriptions = "/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pXRF/pXRF Logbook new.xlsx",
    path_input = "/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pXRF/input",
    path_output = "/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pXRF/output",
    path_standards = "/content/drive/MyDrive/Crossreads B D1/crossreads_petrography_data/pXRF/pXRF Standards.xlsx",
)

## Descriptions

This file lives on Google Drive on the Crossreads team drive. It contains notes about the samples, including the Isic codes.

In [ ]:
xrf.df_descriptions

Loading pXRF descriptions

,M window,M settings,site,day,month,year,cass,inv/id,Isic,count analyses,...,q,r,s,t,u,v,w,x,y,z
instrument,,,,,,,,,,,,,,,,,,,,,
demo,replacement,"15, 35",REF,14,2,2025,,pietra di noto,CN,,...,,,,,,,,,,
demo,replacement,"15, 35",REF,14,2,2025,,comiso,COM,,...,,,,,,,,,,
demo,replacement,"15, 35",CT,27,4,2024,,exmft001,CTexmft001,3.0,...,,,,,,,,,,
demo,replacement,"15, 35",CT,27,3,2024,,exmft003,CTexmft003,4.0,...,,,,,,,,,,
demo,replacement,"15, 35",CT,27,3,2024,,exmft009,CTexmft009,1.0,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
demo,replacement,"15, 35",taormina,22,1,2024,,3555,taormina3555,12.0,...,,,,,,,,,,
demo,replacement,"15, 35",tindari,16,7,2024,,TIND004,tindariTIND004,4.0,...,,,,,,,,,,
demo,replacement,"15, 35",tindari,16,7,2024,,TIND005,tindariTIND005,3.0,...,,,,,,,,,,
demo,replacement,"15, 35",tindari,16,7,2024,,TIND007,tindariTIND007,3.0,...,,,,,,,,,,
demo,replacement,"15, 35",tindari,16,7,2024,,TIND008,tindariTIND008,3.0,...,,,,,,,,,,

## Standards

In [ ]:
xrf.df_standards

Loading pXRF standard values

Unnamed: 0,0CC,10CC,20CC,30CC,40CC,50CC,60CC,70CC,80CC,90CC,100CC
Element,,,,,,,,,,,
SiO2,91.040645,84.721351,78.817028,73.795328,64.449734,55.454155,32.568351,27.167883,21.531343,11.572406,1.000000e-08
K2O,6.002285,5.585656,5.196385,4.865306,4.249153,3.656077,2.147222,1.791171,1.419556,0.762966,1.000000e-08
CaO,0.958449,7.880084,14.336479,19.820316,30.009677,39.799615,64.641336,70.491810,76.593960,87.366212,9.987017e+01
Fe2O3,1.998622,1.812909,1.650108,1.519050,1.291436,1.090152,0.643091,0.549136,0.455141,0.298417,1.298312e-01
Ba,120.000000,107.870481,97.275091,88.771005,74.055316,61.098357,32.508134,26.532239,20.565139,10.640721,0.000000e+00
Ce,195.000000,175.289532,158.072023,144.252883,120.339889,99.284830,52.825719,43.114889,33.418351,17.291171,0.000000e+00
Co,4.000000,3.595683,3.242503,2.959033,2.468511,2.036612,1.083604,0.884408,0.685505,0.354691,0.000000e+00
Cr,12.000000,10.787048,9.727509,8.877100,7.405532,6.109836,3.250813,2.653224,2.056514,1.064072,0.000000e+00
Cu,12.000000,10.790000,9.730000,8.880000,7.410000,6.110000,3.250000,2.650000,2.060000,1.060000,0.000000e+00
Fe,14261.000000,12890.263285,11692.895909,10731.863281,9068.867850,7604.623464,4373.690099,3698.364127,3024.032108,1902.490132,7.000000e+02
Mn,155.000000,140.105962,127.095705,116.653396,98.583757,82.673691,47.567280,40.229379,32.902277,20.715919,7.650000e+00
Ti,540.000000,488.095767,442.756327,406.365924,343.395040,287.950052,165.607726,140.035873,114.501658,72.033418,2.650000e+01
La,109.000000,97.982354,88.358208,80.633663,67.266912,55.497674,29.528222,24.100117,18.680001,9.665321,0.000000e+00
Nb,53.000000,47.642796,42.963165,39.207194,32.707765,26.985108,14.357759,11.718406,9.082936,4.699652,0.000000e+00
Ni,8.000000,7.191365,6.485006,5.918067,4.937021,4.073224,2.167209,1.768816,1.371009,0.709381,0.000000e+00
Pb,40.000000,35.956827,32.425030,29.590335,24.685105,20.366119,10.836045,8.844080,6.855046,3.546907,0.000000e+00
Rb,320.000000,287.654616,259.400243,236.722679,197.480843,162.928951,86.688359,70.752638,54.840371,28.375256,0.000000e+00
Sr,10.000000,14.144252,17.764344,20.669907,25.697767,30.124728,39.893054,41.934818,43.973577,47.364420,5.100000e+01
Th,51.000000,45.844954,41.341914,37.727677,31.473509,25.966802,13.815957,11.276202,8.740184,4.522306,0.000000e+00
V,2.000000,1.797841,1.621252,1.479517,1.234255,1.018306,0.541802,0.442204,0.342752,0.177345,0.000000e+00
Y,143.000000,128.545657,115.919483,105.785447,88.249252,72.808875,38.738860,31.617585,24.506791,12.680192,0.000000e+00
Zn,50.000000,44.946034,40.531288,36.987919,30.856382,25.457649,13.545056,11.055100,8.568808,4.433634,0.000000e+00
Zr,300.000000,269.676203,243.187728,221.927512,185.138290,152.745892,81.270336,66.330598,51.412848,26.601802,0.000000e+00
Hg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## pXRF input data

Two kinds of files:
* "MK" files
    * Filename must start with
    * Only Si, K, Ca, and Fe are included
* "t" files
    * Filenames must start with "t"
    * All elements with linear correlation with standard values (plus HG) are included

pXRF input data is processed in `df_measurements_with_standard_values`, attaching relevant standard values if present from `df_standards`.

In [ ]:
xrf.df_input

         filename                                               text
0  MK termini.txt  SOURCE: MK-ISic000086-a.csv\nKEY: 1.1.00001.1\...
1   t termini.txt  SOURCE: t-ISic000086-a.csv\nKEY: 1.1.00001.1\n...
2     t CC 3x.txt  SOURCE: t-0CC-1.csv\nKEY: 1.1.00001.1\nElement...
3    MK CC 3x.txt  SOURCE: MK-0CC-1.csv\nKEY: 1.1.00001.1\nElemen...

In [ ]:
xrf.df_standards_parsed

ValueError: No objects to concatenate

In [ ]:
xrf.txt_input

In [ ]:
# Plotting mass fraction against standard values to find slope and intercept
xrf.plot()

In [ ]:
# Finding mass fraction against standard values to find slope and intercept
# we add Hg to the list of elements by copying the slope and intercept from Pb
df=xrf.df_linreg
df

In [ ]:
# Measurements with adjusted mass fraction values due to slope and intercept from regression
xrf.df_adjusted

In [ ]:
xrf.df_adjusted.query('Element=="Hg"').sort_values('Mass_fraction')

In [ ]:
xrf.run()